# Mots que les élèves tapent vraiment : sigles et mots courants.
ALIAS = {
 "bac pro installateur en chauffage, climatisation et énergies renouvelables": "ICCER chauffagiste plombier",
 "bac pro maintenance et efficacité énergétique": "MEE chauffagiste",
 "bac pro métiers du froid et des énergies renouvelables": "MFER frigoriste froid",
 "bac pro métiers de l'électricité et de ses environnements connectés": "MELEC électricien électricité",
 "bac pro cybersécurité, informatique et réseaux, électronique": "CIEL SN informatique",
 "bac pro maintenance des systèmes de production connectés": "MSPC MEI maintenance industrielle",
 "bac pro assistance à la gestion des organisations et de leurs activités": "AGORA AGOrA gestion administration secrétariat secrétaire compta comptabilité comptable",
 "bac pro accompagnement, soins et services à la personne": "ASSP aide-soignant aide soignant aide soignante auxiliaire de vie",
 "bac pro animation-enfance et personnes âgées": "AEPA animateur animation",
 "bac pro métiers du commerce et de la vente option A animation et gestion de l'espace commercial": "MCV A MCVA vente commerce vendeur vendeuse caissier caissière magasin",
 "bac pro métiers du commerce et de la vente option B prospection clientèle et valorisation de l'offre commerciale": "MCV B MCVB vente commerce commercial",
 "bac pro métiers de l'accueil": "MA accueil hôtesse",
 "bac pro métiers de la logistique": "logistique magasinier",
 "bac pro organisation de transport de marchandises": "OTM transport",
 "bac pro organisation et réalisation du gros oeuvre": "ORGO maçon maçonnerie",
 "bac pro technicien menuisier agenceur": "TMA menuisier menuiserie",
 "bac pro étude et réalisation d'agencement": "ERA agencement agenceur",
 "bac pro technicien constructeur bois": "TCB charpente charpentier",
 "bac pro technicien de fabrication bois et matériaux associés": "TFBMA menuiserie",
 "bac pro technicien d'études du bâtiment option A études et économie": "TEB EEB études bâtiment économiste",
 "bac pro technicien d'études du bâtiment option B assistant en architecture": "TEB AA architecture",
 "bac pro aménagement et finition du bâtiment": "AFB peintre peinture plaquiste",
 "bac pro travaux publics": "TP",
 "bac pro géomètre": "TGT topographe géomètre",
 "bac pro commercialisation et services en restauration": "CSR serveur service salle",
 "bac pro cuisine": "cuisinier cuisinière",
 "bac pro hygiène, propreté, stérilisation": "HPS",
 "bac pro gestion des pollutions et protection de l'environnement": "GPPE",
 "bac pro laboratoire contrôle qualité": "LCQ laboratoire",
 "bac pro maintenance des véhicules option véhicules légers": "MV MVA mécanique mécanicien mécanicienne mécano auto voiture garage",
 "bac pro maintenance des véhicules option motocycles": "MV moto motard scooter",
 "bac pro maintenance des véhicules option véhicules de transport routier": "MV poids lourds camion bus",
 "bac pro carrossier peintre automobile": "carrosserie carrossier",
 "bac pro technicien en chaudronnerie industrielle": "TCI chaudronnier soudure",
 "bac pro technicien en réalisation de produits mécaniques option réalisation et suivi de productions": "TRPM usinage",
 "bac pro technicien en réalisation de produits mécaniques option réalisation et maintenance des outillages": "TRPM outillage",
 "bac pro artisanat et métiers d'art option communication visuelle plurimédia": "AMA CVPM graphisme graphiste",
 "bac pro artisanat et métiers d'art option métiers de l'enseigne et de la signalétique": "AMA MES enseigne signalétique",
 "bac pro artisanat et métiers d'art option marchandisage visuel": "AMA vitrine étalagiste",
 "bac pro artisanat et métiers d'art option tapissier d'ameublement": "AMA tapissier",
 "bac pro réalisation de produits imprimés et plurimédia option A productions graphiques": "RPIP imprimerie graphisme",
 "bac pro réalisation de produits imprimés et plurimédia option B productions imprimées": "RPIP imprimerie",
 "bac pro métiers de la sécurité": "sécurité agent pompier",
 "bac pro métiers de la coiffure": "coiffeur coiffeuse",
 "bac pro esthétique cosmétique parfumerie": "esthéticienne",
 "bac pro boulanger-pâtissier": "boulangerie pâtisserie",
 "bac pro optique lunetterie": "opticien",
 "CAP accompagnant éducatif petite enfance": "AEPE petite enfance crèche ATSEM",
 "CAP agent accompagnant au grand âge": "AAGA personnes âgées aide soignante auxiliaire de vie EHPAD",
 "CAP équipier polyvalent du commerce": "EPC vente commerce vendeur vendeuse caissier caissière magasin rayon",
 "CAP production et service en restaurations (rapide, collective, cafétéria)": "PSR restauration",
 "CAP commercialisation et services en hôtel-café-restaurant": "CSHCR CS HCR serveur hôtel",
 "CAP interventions en maintenance technique des bâtiments": "IMTB maintenance bâtiment",
 "CAP monteur en installations thermiques": "MIT chauffagiste",
 "CAP monteur en installations sanitaires": "MIS plombier plomberie",
 "CAP installateur en froid et conditionnement d'air": "IFCA froid climatisation",
 "CAP électricien": "électricité",
 "CAP signalétique et décors graphiques": "SDG signalétique",
 "CAP maintenance des véhicules option véhicules légers": "MVA mécanique mécanicien mécanicienne mécano auto voiture garage",
 "CAP maintenance des véhicules option motocycles": "moto motard scooter",
 "CAP opérateur, opératrice logistique": "OL logistique magasinier",
 "CAP réalisations industrielles en chaudronnerie ou soudage option B soudage": "RICS soudeur soudure",
 "CAP réalisations industrielles en chaudronnerie ou soudage option A chaudronnerie": "RICS chaudronnier",
 "CAP métiers de la coiffure": "coiffeur coiffeuse",
 "CAP esthétique cosmétique parfumerie": "esthéticienne",
 "CAP cuisine": "cuisinier cuisinière",
 "CAP agent de sécurité": "sécurité vigile",
 "CAP propreté et prévention des biocontaminations": "APH propreté nettoyage",
 "CAP peintre applicateur de revêtements": "peintre peinture",
 "CAP menuisier fabricant": "menuiserie",
 "CAP menuisier installateur": "menuiserie",
 "CAPa jardinier-paysagiste": "jardinier paysagiste espaces verts",
}
ICON = {
 "Bâtiment et travaux publics": "🧱", "Énergie, électricité, chauffage": "⚡", "Automobile, moto, poids lourds, aéronautique": "🚗",
 "Industrie, mécanique, métallerie": "⚙️", "Bois, ameublement, métiers d'art": "🪚", "Communication visuelle, impression, audiovisuel": "🖨️",
 "Commerce et vente": "🛒", "Alimentation, métiers de bouche": "🥖", "Hôtellerie, restauration": "🍽️", "Santé, social, aide à la personne": "🩺",
 "Coiffure, esthétique, bien-être": "💇", "Transport, logistique": "🚚", "Gestion, administration, accueil": "💼", "Sécurité": "🛡️",
 "Propreté, environnement": "♻️", "Espaces verts, agriculture, animaux": "🌿", "Informatique, numérique, télécoms": "💻",
 "Mode, textile, cuir": "🧵", "Sport, animation, culture": "⚽",
}

ALIAS["bac pro technicien menuisier agenceur"] += " MA"
# Familles de métiers de 2nde pro : l'élève voit les entreprises de tous les bacs pro de sa famille.
FAMILLES = {
 "Transitions numérique et énergétique (TNE)": ("TNE 2nde TNE", ["bac pro métiers de l'électricité et de ses environnements connectés", "bac pro installateur en chauffage, climatisation et énergies renouvelables", "bac pro métiers du froid et des énergies renouvelables", "bac pro maintenance et efficacité énergétique", "bac pro cybersécurité, informatique et réseaux, électronique"]),
 "Études et modélisation numérique du bâtiment (EMNB)": ("MNB EMNB 2nde MNB", ["bac pro technicien d'études du bâtiment option A études et économie", "bac pro technicien d'études du bâtiment option B assistant en architecture", "bac pro géomètre"]),
 "Agencement, menuiserie et ameublement (MAMA)": ("MAMA 2nde MAMA", ["bac pro technicien menuisier agenceur", "bac pro étude et réalisation d'agencement", "bac pro technicien de fabrication bois et matériaux associés"]),
 "Construction durable, bâtiment et travaux publics": ("CDBTP 2nde bâtiment", ["bac pro aménagement et finition du bâtiment", "bac pro organisation et réalisation du gros oeuvre", "bac pro travaux publics", "bac pro interventions sur le patrimoine bâti option A maçonnerie", "bac pro menuiserie aluminium-verre", "bac pro ouvrages du bâtiment : métallerie"]),
 "Gestion administrative, transport et logistique (GATL)": ("GATL 2nde GATL", ["bac pro assistance à la gestion des organisations et de leurs activités", "bac pro métiers de la logistique", "bac pro organisation de transport de marchandises"]),
 "Relation client (MRC)": ("MRC 2nde MRC vente commerce accueil", ["bac pro métiers du commerce et de la vente option A animation et gestion de l'espace commercial", "bac pro métiers du commerce et de la vente option B prospection clientèle et valorisation de l'offre commerciale", "bac pro métiers de l'accueil"]),
 "Hôtellerie-restauration": ("HR 2nde hôtellerie restauration", ["bac pro cuisine", "bac pro commercialisation et services en restauration"]),
 "Alimentation": ("2nde alimentation", ["bac pro boulanger-pâtissier", "bac pro technicien conseil vente en alimentation (produits alimentaires et boissons)"]),
 "Beauté et bien-être": ("2nde beauté", ["bac pro esthétique cosmétique parfumerie", "bac pro métiers de la coiffure"]),
 "Maintenance des matériels et des véhicules": ("MMV 2nde maintenance véhicules", ["bac pro maintenance des véhicules option véhicules légers", "bac pro maintenance des véhicules option motocycles", "bac pro maintenance des véhicules option véhicules de transport routier", "bac pro maintenance des matériels option B matériels de construction et de manutention"]),
 "Réalisation d'ensembles mécaniques et industriels (MREMI)": ("MREMI 2nde mécanique", ["bac pro technicien en réalisation de produits mécaniques option réalisation et suivi de productions", "bac pro technicien en chaudronnerie industrielle", "bac pro modélisation et prototypage 3D", "bac pro microtechniques"]),
 "Pilotage et maintenance d'installations automatisées (PMIA)": ("PMIA 2nde", ["bac pro maintenance des systèmes de production connectés", "bac pro pilote de ligne de production", "bac pro procédés de la chimie, de l'eau et des papiers-cartons"]),
 "Industries graphiques et communication": ("2nde industries graphiques", ["bac pro réalisation de produits imprimés et plurimédia option A productions graphiques", "bac pro réalisation de produits imprimés et plurimédia option B productions imprimées", "bac pro façonnage de produits imprimés, routage"]),
 "Aéronautique": ("2nde aéronautique", ["bac pro aéronautique option avionique", "bac pro aéronautique option structure", "bac pro aéronautique option systèmes", "bac pro aviation générale"]),
}

# Autres diplômes du lycée (hors CAP / bac pro) : brevets des métiers d'art
AUTRES = {
 "Ébéniste": ("BMA", "BMA ébéniste ébénisterie", ["Ébénisterie, meubles, restauration de meubles", "Sièges, réparation de meubles", "Menuiserie bois, agencement", "Tapisserie, décoration textile", "Ateliers de décors et de musées", "Ateliers associatifs du bois"]),
 "Arts graphiques option signalétique": ("BMA", "BMA signalétique enseigne graphisme", ["Enseignes, signalétique, marquage", "Imprimerie, prépresse, reliure", "Publicité, design graphique", "Ateliers de décors et de musées"]),
}

# Secteurs imposés pour une famille de 2nde (au lieu de la réunion des secteurs de ses bacs pro)
FAMILLES_SECTEURS = {
 "Agencement, menuiserie et ameublement (MAMA)": ["Menuiserie bois, agencement", "Menuiserie métallique, serrurerie", "Ébénisterie, meubles, restauration de meubles", "Sièges, réparation de meubles", "Tapisserie, décoration textile", "Ateliers de décors et de musées", "Ateliers associatifs du bois"],
}
