# Corrections manuelles du rangement par domaine (relu le 06/10/2026)
C={
"CAP boulanger":"alimentation","CAP pâtissier":"alimentation","CAP crémier-fromager":"alimentation,commerce",
"CAP carreleur mosaïste":"batiment","CAP conducteur d'engins de travaux publics et carrières":"batiment,transport",
"CAP constructeur de réseaux de canalisations de travaux publics":"batiment,environnement",
"CAP esthétique cosmétique parfumerie":"beaute","CAP fleuriste":"nature,commerce",
"CAP interventions en maintenance technique des bâtiments":"batiment,energie",
"CAP maintenance des matériels option A matériels agricoles":"auto,nature",
"CAP maintenance des matériels option B matériels de construction et de manutention":"auto",
"CAP maintenance des matériels option C matériels d'espaces verts":"auto,nature",
"CAP maintenance des véhicules option motocycles":"auto","CAP maintenance des véhicules option véhicules légers":"auto",
"CAP maintenance des véhicules option véhicules de transport routier":"auto,transport",
"CAP carrossier automobile":"auto","CAP peintre automobile":"auto",
"CAP menuisier aluminium-verre":"batiment,bois","CAP peintre applicateur de revêtements":"batiment",
"CAP métiers de l'entretien des textiles option A blanchisserie":"mode","CAP métiers de l'entretien des textiles option B pressing":"mode",
"CAP métiers de la mode - vêtement flou":"mode","CAP métiers de la mode - chapelier-modiste":"mode,arts",
"CAP staffeur ornemaniste":"batiment,arts","CAP électricien":"energie,batiment",
"CAP propreté et prévention des biocontaminations":"environnement",
"CAPa services aux personnes et vente en espace rural":"sante,commerce",
"bac pro artisanat et métiers d'art option marchandisage visuel":"arts,commerce",
"bac pro boulanger-pâtissier":"alimentation","bac pro carrossier peintre automobile":"auto",
"bac pro conduite et gestion de l'entreprise agricole":"nature","bac pro cybersécurité, informatique et réseaux, électronique":"numerique",
"bac pro esthétique cosmétique parfumerie":"beaute","bac pro métiers de la coiffure":"beaute",
"bac pro gestion des milieux naturels et de la faune":"nature,environnement","bac pro géomètre":"batiment",
"bac pro laboratoire contrôle qualité":"labo,industrie",
"bac pro maintenance des matériels option A matériels agricoles":"auto,nature",
"bac pro maintenance des matériels option B matériels de construction et de manutention":"auto",
"bac pro maintenance des matériels option C matériels d'espaces verts":"auto,nature",
"bac pro maintenance des véhicules option motocycles":"auto","bac pro maintenance des véhicules option véhicules légers":"auto",
"bac pro maintenance des véhicules option véhicules de transport routier":"auto,transport",
"bac pro construction et aménagement de véhicules":"auto,industrie",
"bac pro maintenance et efficacité énergétique":"energie","bac pro menuiserie aluminium-verre":"batiment,bois",
"bac pro métiers de l'électricité et de ses environnements connectés":"energie,numerique",
"bac pro procédés de la chimie, de l'eau et des papiers-cartons":"labo,industrie",
"bac pro réalisation de produits imprimés et plurimédia option A productions graphiques":"arts",
"bac pro réalisation de produits imprimés et plurimédia option B productions imprimées":"arts",
"bac pro services aux personnes et animation dans les territoires":"sante",
"bac pro technicien conseil vente en alimentation (produits alimentaires et boissons)":"alimentation,commerce",
"bac pro technicien d'études du bâtiment option A études et économie":"batiment",
"bac pro technicien d'études du bâtiment option B assistant en architecture":"batiment",
"bac pro technicien de fabrication bois et matériaux associés":"bois",
"bac pro technicien en réalisation de produits mécaniques option réalisation et suivi de productions":"industrie",
"bac pro étude et réalisation d'agencement":"bois,batiment,arts",
"classe de 2de professionnelle alimentation, bio-industries et laboratoire":"alimentation,labo,industrie",
"classe de 2de professionnelle métiers de l'alimentation":"alimentation",
"classe de 2de professionnelle métiers de la beauté et du bien-être":"beaute",
"classe de 2de professionnelle métiers des transitions numérique et énergétique":"energie,numerique,batiment",
"classe de 2de professionnelle métiers des études et de la modélisation numérique du bâtiment":"batiment",
"classe de 2de professionnelle métiers du pilotage et de la maintenance d'installations automatisées":"industrie",
"classe de 2de professionnelle nature-jardin-paysage-forêt":"nature,environnement",
"classe de 2de professionnelle productions":"nature",
"classe de 2de professionnelle métiers de la maintenance des matériels et des véhicules":"auto",
"classe de 2de professionnelle métiers des industries graphiques et de la communication":"arts",
}
