# Classes de terminale du lycée Eugène Hénaff -> formations suivantes citées par l'Onisep
# (rubrique « Exemple(s) de formation(s) » de chaque fiche diplôme, lue le 06/10/2026)
SUITES = {
 "iccer": ("Bac pro ICCER","bac pro installateur en chauffage, climatisation et énergies renouvelables","FOR.7017",
   ["CS technicien en énergies renouvelables option B énergie thermique","BTS contrôle industriel et régulation automatique",
    "BTS fluides, énergies, domotique option A génie climatique et fluidique","BTS fluides, énergies, domotique option B froid et conditionnement d'air",
    "BTS maintenance des systèmes option B systèmes énergétiques et fluidiques",
    "BP installateur, dépanneur en froid et conditionnement d'air","BP monteur en installations du génie climatique et sanitaire"]),
 "mee": ("Bac pro MEE","bac pro maintenance et efficacité énergétique","FOR.12949",
   ["CS technicien des services à l'énergie","BTS fluides, énergies, domotique option A génie climatique et fluidique",
    "BTS fluides, énergies, domotique option B froid et conditionnement d'air","BTS maintenance des systèmes option B systèmes énergétiques et fluidiques",
    "BP monteur en installations du génie climatique et sanitaire"]),
 "tma": ("Bac pro TMA","bac pro technicien menuisier agenceur","FOR.3119",
   ["BTS conseil et commercialisation de solutions techniques","BTS développement et réalisation bois","BTS systèmes constructifs bois et habitat"]),
 "era": ("Bac pro ERA","bac pro étude et réalisation d'agencement","FOR.2883",["BTS étude et réalisation d'agencement"]),
 "eeb": ("Bac pro EEB","bac pro technicien d'études du bâtiment option A études et économie","FOR.5601",
   ["BTS bâtiment","BTS enveloppe des bâtiments : conception et réalisation","BTS management économique de la construction"]),
 "geometre": ("Bac pro Géomètre","bac pro géomètre","FOR.9977",
   ["BTS métiers du géomètre-topographe et de la modélisation numérique","BTS travaux publics"]),
 "mit": ("CAP MIT","CAP monteur en installations thermiques","FOR.997",
   ["CAP installateur en froid et conditionnement d'air","CAP monteur en installations sanitaires","CS maintenance des équipements thermiques individuels",
    "bac pro installateur en chauffage, climatisation et énergies renouvelables","bac pro maintenance et efficacité énergétique",
    "BP installateur, dépanneur en froid et conditionnement d'air","BP métiers de la piscine","BP monteur en installations du génie climatique et sanitaire"]),
 "sdg": ("CAP Signalétique","CAP signalétique et décors graphiques","FOR.1396",
   ["bac pro artisanat et métiers d'art option communication visuelle plurimédia","BMA arts graphiques option A signalétique","BMA arts graphiques option B décor peint"]),
 "ebeniste": ("CAP Ébéniste","CAP ébéniste","FOR.1088",
   ["CAP arts du bois option marqueteur","CAP arts du bois option sculpteur ornemaniste","CAP arts du bois option tourneur","CAP dessinateur industriel d'ameublement",
    "bac pro artisanat et métiers d'art - facteur d'orgues option organier","BMA ébéniste","BNMA ébénisterie","BTM ébéniste","Diplôme de fin d'études secondaires des métiers d'art"]),
 "bma-ebeniste": ("BMA Ébéniste","BMA ébéniste","FOR.1358",
   ["bac pro artisanat et métiers d'art - facteur d'orgues option organier","DN MADE mention matériaux","DN MADE mention objet"]),
 "bma-signaletique": ("BMA Signalétique","BMA arts graphiques option A signalétique","FOR.5664",
   ["DN MADE mention événement","DN MADE mention graphisme","DN MADE mention ornement"]),
}
